### ISSUE TITLE
Web Application for LADy

### ISSUE THREAD

**Issue by farinamhz** [fani-lab/LADy#32]
Hi @impedaka,

Welcome to LADy :)

This is an issue page to log your progress in developing the web app.

Please let us know if you have any concerns or questions.

@hosseinfani

**Comment by impedaka** [comment]
@hosseinfani 

Installing a lower version of gensim fixed the issue, but I think I found another issue regarding gensim. It happens when we load the model. I installed gensim 4.2.0 and the latest version is 4.3.1
![image](https://github.com/fani-lab/LADy/assets/75595719/1e3bb36b-fe6d-42d4-b1c0-3781d48e0713)
![image](https://github.com/fani-lab/LADy/assets/75595719/5a084769-a80f-46fd-8c82-5ce290a82369)

The translate and backtranslate function worked though
![image](https://github.com/fani-lab/LADy/assets/75595719/4acc280f-d24b-431c-b6e9-bb1639a9f77b)
```py
     print('translated',tranlated_review )
     print("back",backtranslated_review )
     print("sem", semantic_similarity )
```
We might need to change the code or I could be installing the wrong gensim version

**Comment by impedaka** [comment]
@farinamhz any updates?

**Comment by farinamhz** [comment]
Hey @impedaka ,
I added your name to the authors,
Now, as you may know, we are going to deploy the web application, so prior to that, you can get the latest version of the LADy and let me know if there is any problem with the installation and running now.
If there is any, I will update it, and once it is ok for you, we will go for the next steps of our web application.

**Comment by impedaka** [comment]
Alright, thank you!

**Comment by farinamhz** [comment]
Also, please check the new readme, Alice, and let me know if you think any change is needed and can improve it.
@impedaka

**Comment by impedaka** [comment]
@farinamhz 
sorry for the late reply. i ran main.py from the latest code base with no problems. I'd like to hear the next steps :)

README.md looks good.  some of the links are invalid like in https://github.com/impedaka/LADy-1#srccmn
> Sample pickle files for a toy dataset: [./output/toy.2016SB5/ABSA16_Restaurants_Train_SB1_v2.xml](https://github.com/impedaka/LADy-1/blob/main/output/toy.2016SB5/ABSA16_Restaurants_Train_SB1_v2.xml),

and https://github.com/impedaka/LADy-1#results
<html><body>
<!--StartFragment-->

dataset | review files (english, chinese, farsi, arabic, french, german, spanish, and all) and results' directory
-- | --
semeval-14-laptop | ./output/Semeval-14/Laptop/                                                                                                                                                                                                                                             22.0 MB
semeval-14-restaurant | ./output/Semeval-14/Restaurants/                                                                                                                                                                                                                                        22.2 MB
semeval-15-restaurant | ./output/2015SB12/    53.1 GB
semeval-16-restaurant | ./output/2016SB5/    103 MB
toy | ./output/toy.2016SB5/ 64.6 MB

https://uwin365.sharepoint.com/sites/cshfrg-ReviewAnalysis/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2Fcshfrg%2DReviewAnalysis%2FShared%20Documents%2FLADy%2FLADy0%2E1%2E0%2E0%2Foutput%2Ftoy%2E2016SB5&viewid=4cd69493%2D951c%2D47b5%2Db34a%2Dc1cdbf3a0412

Uwin account required I think

**Comment by farinamhz** [comment]
Hey @impedaka,
No worries. Thank you very much for the time you put into this task.
I will check and change the mentioned links and let you know the next step tomorrow.

**Comment by impedaka** [comment]
I can run the web app on local host, Are we using the same layout as the
previous website I made? The website code isn't included in the main
project, should I add it or make a new one?

**Comment by farinamhz** [comment]
I asked so I could run on local host and take a look at the layout, so we can modify it if needed.
It would be great if you add it to the existing codeline. @impedaka

**Comment by impedaka** [comment]
I can add it, not all of the functionality is working however. You'll need
to run both the backend and frontend at the same time.

In LADy/src/web/backend
install Flask and flask_cors
run python app.py
to run the backend server

install nodejs for the frontend if you havent already
In LADy/src/web/frontend
npm install
npm run dev
it'll run on localhost:3000

Sorry if this is complicated. I'm using the models from before, so the
backend isn't up to date.
I'll make a PR :)

**Comment by farinamhz** [comment]
Hey @impedaka, thank you again for the updates, that is great, and I asked @hosseinfani if we can accept the PR now.

Meanwhile, I will share a google doc for the web app and list whatever we need as modifications or new requirements there so that we can explain and update with @hosseinfani.

**Comment by impedaka** [comment]
![image](https://github.com/fani-lab/LADy/assets/75595719/5b6918d5-62d2-455d-bb94-ab49d024dc61)
![image](https://github.com/fani-lab/LADy/assets/75595719/4d30edde-620a-4b7d-a598-646e46ab0015)

I made some changes to the design. Let me know what you think. 

Personally, I think the image would look nicer if it were on the right side and not transparent. I can make a preview if you're interested. I'm still making minor adjustments to the website to make it more user friendly. Update me on the google docs for whatever needs to be done :)

**Comment by farinamhz** [comment]
Hey @impedaka,
Great, thank you very much for the updates.
- regarding the image, I agree, and I think for now, we do not need the photo.
- regarding the emoji for the webpage, is it possible that we make it transparent so if we have a different color, like purple in your case or any dark one, we do not have the white area surrounding it?
- regarding google docs, I just shared it with you.

**Comment by impedaka** [comment]
@farinamhz 
> regarding the emoji for the webpage, is it possible that we make it transparent so if we have a different color, like purple in your case or any dark one, we do not have the white area surrounding it?

I will make it transparent :)

> regarding google docs, I just shared it with you.

Thank you!

**Comment by impedaka** [comment]
@farinamhz 

Good news! I got the backtranslation working without changing the numpy version. Before it didn't work because it relied on a older version of numpy. Downgrading numpy caused other problems with other libraries and functions.

I just updated networkx to 3.1
![image](https://github.com/fani-lab/LADy/assets/75595719/3d3fcb6c-7314-4260-8de8-2d91f65e7433)
hopefully it doesn't negatively impact anything. So far no errors for me

![image](https://github.com/fani-lab/LADy/assets/75595719/7195f54d-9f97-436f-8a34-8b8aeeb00b7d)

```py
    settings = {'nllb': 'facebook/nllb-200-distilled-600M', 'max_l': 1024, 'device': 'cpu'}
    res = r.translate('pes_Arab', settings)
    tranlated_review = res[0].get_txt()
    backtranslated_review = res[1].get_txt()
    semantic_similarity = res[2]
    print('translated',tranlated_review )
    print("back",backtranslated_review )
    print("sem", semantic_similarity )
```

before I fixed it, this was the error:
```
Traceback (most recent call last):
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Qin\LADy-1\src\web\backend\app.py", line 48, in api
    res = r.translate('pes_Arab', settings)
  File "C:\Users\Qin\LADy-1\src\cmn\review.py", line 67, in translate
    translated_obj.aos, _ = self.semalign(translated_obj)  
  File "C:\Users\Qin\LADy-1\src\cmn\review.py", line 85, in semalign
    from simalign import SentenceAligner
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\simalign\__init__.py", line 1, in <module>
    from .simalign import EmbeddingLoader, SentenceAligner 
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\simalign\simalign.py", line 13, in <module>
    import networkx as nx
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\networkx\__init__.py", line 115, in <module>
    import networkx.readwrite
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\networkx\readwrite\__init__.py", line 15, in <module>
    from networkx.readwrite.graphml import *
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\networkx\readwrite\graphml.py", line 314, in <module>
    class GraphML(object):
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\networkx\readwrite\graphml.py", line 346, in GraphML
    (np.int, "int"), (np.int8, "int"),
  File "C:\Users\Qin\LADy-1\venv\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
void this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.

The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations  
```

**Comment by impedaka** [comment]
![image](https://github.com/fani-lab/LADy/assets/75595719/c120295f-5b57-4ed6-a73a-8360290512e7)
![image](https://github.com/fani-lab/LADy/assets/75595719/fed9fff7-c944-45fc-a71b-ef9086024852)

I will update you on the design for the new backtranslation and translation function. Let me know your ideas!

>Adding different metrics results to the results displayed (we have success@k, but we need map@k, recall@k, ndcg@k, and precision@k, which are all in the output available), it can be a choice after the results are displayed to be changed.

also I'm not sure how to use different metric results. Either I spend more time figuring it out, or you can show me :)

**Comment by farinamhz** [comment]
Hey @impedaka,
Great! Thank you for letting me know of the issue and update on the fix.
__
Nice! I think if we have sth like:

Translated (Farsi): "..."
Backtranslated (English): "..."

With a suitable space of more than one line between these two parts, as characters may differ in size.

For the augmentation, I am going to talk with @hosseinfani first, as we should provide different models in this regard. Otherwise, we need to mention all the results will be based on the augmentation, and in that case, we need to remove the checkbox. Anyway, thank you for adding it. I'll update you on this.

I will provide an example of the results in a few minutes for you to tell you about the metrics.

**Comment by farinamhz** [comment]
When we do the inference part, a file named model.pred.eval.mean like this [example](https://github.com/fani-lab/LADy/blob/main/output/toy.2016SB5/5/lda/model.pred.eval.mean.0.0.csv) will be created in the directory of that model.

There are values of different metrics@k in this file, including precision which (we called P there), recall, map_cut, NDCG, and success metrics.

Now, we have the success metric's value for the bar in front of each word in the current version of the web app and we are thinking of showing the values of metrics for a specific model.

But I think maybe we don't need it in the web app in this scenario we just find the inference for one review.
What do you think @hosseinfani?

**Comment by farinamhz** [comment]
@hosseinfani'
I would appreciate your suggestion on this.

I think as they will still be generated even for one review, I think for now, we have two options:

- provide a list of metrics to choose the metric that we want, and after making the inference, show the results of, for example, success@k in the bar plot that we have and mention each value is, for example, success@1, success@2, or success@k. And whatever metric is provided, show the result of the bar plot for that metric, so we do not show the results for all the metrics at once in several plots together on one page. Instead, we set a default metric as success and show the success values first, like now. Then if the user changes the metric, the bar plot will be changed to show that value.

- the second option is just showing the results for the trained model.

**Comment by hosseinfani** [comment]
@farinamhz @impedaka 
where are the random review is coming from? if we know the truth about the aspect, we need to report the metrics. We simply calculate the metric given we have the truth. 

if the input review is out of our datasets, then we don't know the truth. So, there is no need to report the metric as we don't know the truth. So, we just show the top results and the value of the scores. We can call it `confidence score'.

@impedaka 
 can you make the title like: LADy: Latent Aspect Detection from Online Unsolicited Reviews

**Comment by impedaka** [comment]
>  where are the random review is coming from? if we know the truth about the aspect, we need to report the metrics. We simply calculate the metric given we have the truth.

Random review is from the toy dataset.

> can you make the title like: LADy: Latent Aspect Detection from Online Unsolicited Reviews

Yes1

**Comment by impedaka** [comment]
@farinamhz 
Sorry for not updating for a long time (I've been on a family trip).
I got the random reviews from https://github.com/impedaka/LADy/blob/main/data/raw/semeval/reviews.csv and not from https://github.com/fani-lab/LADy/blob/main/output/toy.2016SB5/reviews.pkl or https://github.com/fani-lab/LADy/tree/main/data/raw/mams

I'll have to change my code so that it can match the prediction and the truth, and create a metric off of it. Opening reviews.pkl (https://github.com/fani-lab/LADy/blob/main/output/toy.2016SB5/reviews.pkl )
![image](https://github.com/fani-lab/LADy/assets/75595719/47ed5056-fe7e-4641-aa0e-acbbc607747d)

This is my code for opening the review.pkl file:
```py
reviews = pickle.load(file)
cnt = 0
for item in enumerate(reviews):
    print(cnt, item[1].get_txt())
    cnt += 1
```
I'm assuming the truth for each review is in the file as well? I don't know how to view it.

Also, I made the translation and back translation from the website more presentable.

**Comment by farinamhz** [comment]
Hey @impedaka,
Thank you very much for the updates.

Regarding the review file;
- You can use this [toy dataset](https://github.com/fani-lab/LADy/blob/main/output/toy.2016SB5/reviews.pkl).
- And for reading the review files and finding the truth for each review;
In case of having a list of reviews, you can get the list of aspects for each review like this as we have a triplet of aspects list, opinion, and sentiment for each review:

```py
r_aspects = [[w for a, o, s in sent for w in a] for sent in r.get_aos()]  # result will be like this: [['service', 'food'], ['service'], ...]
```

You can check the inference method for more details: [inference method link](https://github.com/fani-lab/LADy/blob/8b1422da60c723214e9cd1c6bd08b744cba2a95e/src/aml/mdl.py#L31)

Let me know if you have more questions on this.
Also, once you are done with updating this, let me know, please, so we can go forward with the other tasks on the web app.

**Comment by impedaka** [comment]
Thank you, I will do that c:

**Comment by farinamhz** [comment]
Hey Alice,
Do we have any updates on the web app?
@impedaka

**Comment by impedaka** [comment]
No, not yet. School has been way busier than expected. Sorry :c

I’ll see if I can work on it during the weekend

**Comment by farinamhz** [comment]
No problem, @impedaka! Take your time and focus on school. Thanks for letting me know :)

If you can manage to work on it over the weekend and share photos or confirm its completion so that I can take the snapshots, that would be fantastic.

Meanwhile, We plan to submit our paper (which we withdrew last time), most likely within the next two weeks and want to mention our web app there.

**Comment by impedaka** [comment]
Sounds good!

**Comment by impedaka** [comment]
@farinamhz 
Sorry, I wasn't able to work on it during the weekend.
Did a small video demo:
https://drive.google.com/file/d/1yzSMTucXd1kbKYDzi172W2-__lyVJuuE/view?usp=sharing

![image](https://github.com/fani-lab/LADy/assets/75595719/453c9de8-ec32-4518-9764-852a2223f4a3)

I'll try to work on it during the weekdays, but I probably won't have too much time either

**Comment by farinamhz** [comment]
Thank you very much, @impedaka, for the demo on the web app. That's great!

**Comment by farinamhz** [comment]
Also, could you kindly share your thoughts on the amount of updates and acceptable features of the web app for the resource paper, @hosseinfani? so we can work on the paper writeup with @3ripleM.
